-- V1__
CREATE TABLE Person (
  id VARCHAR(63) PRIMARY KEY, 
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(50) NOT NULL,
  birth_date DATE NOT NULL,
  mother_name VARCHAR(100) NOT NULL,
  father_name VARCHAR(100) NOT NULL,
  telephone VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
